# Generated by Django 5.2.4 on 2025-07-16 12:33

import frontend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0006_alter_product_freedelivery_alter_product_images_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="alt",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="image",
            name="src",
            field=models.ImageField(upload_to=frontend.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name="review",
            name="rate",
            field=models.IntegerField(default=0),
        ),
    ]
