# Generated by Django 5.2.4 on 2025-07-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0008_alter_image_src_remove_product_images_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.FloatField(default=0),
        ),
    ]
