# Generated by Django 5.2.4 on 2025-07-19 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0011_remove_category_subcategories_category_subcategories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="images",
        ),
        migrations.AddField(
            model_name="category",
            name="images",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="frontend.image",
            ),
        ),
    ]
