# Generated by Django 5.2.4 on 2025-07-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0013_rename_images_category_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
