# Generated by Django 5.2.4 on 2025-07-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0015_basket_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="basket",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
