# Generated by Django 5.2.4 on 2025-07-20 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0016_basket_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basket",
            name="products",
        ),
        migrations.AddField(
            model_name="basket",
            name="products",
            field=models.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="frontend.product",
            ),
        ),
    ]
