# Generated by Django 5.2.4 on 2025-07-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0022_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="user",
        ),
        migrations.AddField(
            model_name="payment",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="payment",
            name="code",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="month",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="number",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="year",
            field=models.IntegerField(blank=True),
        ),
    ]
