# Generated by Django 5.2.4 on 2025-07-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "frontend",
            "0023_remove_payment_user_payment_name_alter_payment_code_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="deliveryType",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
