# Generated by Django 5.2.4 on 2025-07-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0024_alter_order_deliverytype"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Available",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
