# Generated by Django 5.2.4 on 2025-07-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0025_product_available_product_limited"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basket",
            name="products",
        ),
        migrations.AddField(
            model_name="basket",
            name="products",
            field=models.ManyToManyField(blank=True, to="frontend.product"),
        ),
    ]
