# Generated by Django 5.2.4 on 2025-08-01 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0027_basket_total_price_remove_basket_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='frontend.review'),
        ),
    ]
