# Generated by Django 5.2.4 on 2025-08-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0030_alter_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(blank=True, to='frontend.tag'),
        ),
    ]
