# Generated by Django 5.2.4 on 2025-08-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0032_product_datefrom_product_dateto_product_saleprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="dateFrom",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="dateTo",
            field=models.DateField(blank=True, null=True),
        ),
    ]
