# Generated by Django 5.2.4 on 2025-08-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0034_alter_product_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="products",
        ),
        migrations.AddField(
            model_name="order",
            name="basket",
            field=models.ManyToManyField(blank=True, to="frontend.basket"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
