# Generated by Django 5.2.4 on 2025-08-14 08:15

import frontend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0038_alter_order_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="src",
            field=models.ImageField(upload_to=frontend.models.user_directory_path),
        ),
        migrations.RemoveField(
            model_name="product",
            name="specifications",
        ),
        migrations.AddField(
            model_name="product",
            name="specifications",
            field=models.ManyToManyField(blank=True, to="frontend.specification"),
        ),
    ]
