# Generated by Django 5.2.4 on 2025-08-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0041_alter_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="subcategory",
        ),
        migrations.AlterField(
            model_name="category",
            name="subcategories",
            field=models.ManyToManyField(blank=True, to="frontend.category"),
        ),
    ]
