# Generated by Django 5.2.4 on 2025-08-14 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0042_remove_product_subcategory_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subcategories",
        ),
    ]
