# Generated by Django 5.2.4 on 2025-07-15 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_category_specification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('fullDescription', models.TextField(blank=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('count', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('freeDelivery', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.category')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.image')),
                ('reviews', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.review')),
                ('specifications', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.specification')),
                ('tags', models.ManyToManyField(to='frontend.tag')),
            ],
        ),
    ]
