# Generated by Django 5.2.4 on 2025-07-15 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0005_alter_product_date_alter_product_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="freeDelivery",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="frontend.image",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="reviews",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="frontend.review",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="specifications",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="frontend.specification",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(blank=True, null=True, to="frontend.tag"),
        ),
    ]
