# Generated by Django 5.2.4 on 2025-07-19 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0009_alter_product_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="images",
            field=models.ManyToManyField(blank=True, to="frontend.image"),
        ),
        migrations.CreateModel(
            name="Subcategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("images", models.ManyToManyField(blank=True, to="frontend.image")),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="subcategories",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="frontend.subcategories",
            ),
        ),
    ]
