# Generated by Django 5.2.4 on 2025-07-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0010_category_images_subcategories_category_subcategories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="subcategories",
        ),
        migrations.AddField(
            model_name="category",
            name="subcategories",
            field=models.ManyToManyField(blank=True, to="frontend.subcategories"),
        ),
    ]
