# Generated by Django 5.2.4 on 2025-07-19 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0012_remove_category_images_category_images"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="images",
            new_name="image",
        ),
        migrations.RemoveField(
            model_name="subcategories",
            name="images",
        ),
        migrations.AddField(
            model_name="subcategories",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="frontend.image",
            ),
        ),
    ]
