# Generated by Django 5.2.4 on 2025-07-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0014_alter_product_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="basket",
            name="count",
            field=models.IntegerField(default=0),
        ),
    ]
