# Generated by Django 5.2.4 on 2025-07-25 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0020_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="frontend.profile"
            ),
        ),
    ]
