# Generated by Django 5.2.4 on 2025-07-27 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0021_alter_order_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(blank=True, max_length=20)),
                ("month", models.IntegerField(blank=True, max_length=20)),
                ("year", models.IntegerField(blank=True, max_length=4)),
                ("code", models.IntegerField(blank=True, max_length=3)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="frontend.profile",
                    ),
                ),
            ],
        ),
    ]
