# Generated by Django 5.2.4 on 2025-08-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0033_alter_product_datefrom_alter_product_dateto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
