# Generated by Django 5.2.4 on 2025-08-10 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0035_remove_order_products_order_basket_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basket",
            name="count",
        ),
        migrations.RemoveField(
            model_name="basket",
            name="products",
        ),
        migrations.RemoveField(
            model_name="order",
            name="basket",
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="frontend.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="basket",
            name="item",
            field=models.ManyToManyField(blank=True, to="frontend.cartitem"),
        ),
        migrations.AddField(
            model_name="order",
            name="item",
            field=models.ManyToManyField(blank=True, to="frontend.cartitem"),
        ),
    ]
