# Generated by Django 5.2.4 on 2025-08-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0036_remove_basket_count_remove_basket_products_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basket",
            name="item",
            field=models.ManyToManyField(
                blank=True, related_name="basket", to="frontend.cartitem"
            ),
        ),
    ]
