# Generated by Django 5.2.4 on 2025-08-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0037_alter_basket_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="item",
            field=models.ManyToManyField(
                blank=True, related_name="order", to="frontend.cartitem"
            ),
        ),
    ]
