# Generated by Django 5.2.4 on 2025-08-14 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0039_alter_image_src_remove_product_specifications_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="frontend.subcategories",
            ),
        ),
    ]
